#!/usr/bin/env node
/**
 * Memory System File Generator
 * Creates all Ruflow memory system files in the correct locations.
 * Run: node scripts/memory-db/gen.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');

function writeFile(relPath, content) {
  const full = path.join(ROOT, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content, 'utf-8');
  console.log('  Created: ' + relPath + ' (' + content.length + ' bytes)');
}

console.log('Generating Ruflow memory system files...');
console.log('Root: ' + ROOT);

// =====================================================================
// FILE 2: .claude/helpers/memory-query.cjs
// =====================================================================
writeFile('.claude/helpers/memory-query.cjs', [
  '#!/usr/bin/env node',
  '/**',
  ' * Ruflow Memory System - Query Helper',
  ' * Provides functions to store and retrieve sessions, tasks, learnings,',
  ' * errors, skills usage, and knowledge entries.',
  ' */',
  '',
  "const path = require('path');",
  "const { getDb, saveDb, DB_PATH } = require(path.join(__dirname, 'memory-init.cjs'));",
  '',
  'function now() { return new Date().toISOString(); }',
  '',
  'function queryOne(db, sql, params) {',
  '  const result = db.exec(sql, params || []);',
  '  if (!result.length || !result[0].values.length) return null;',
  '  const cols = result[0].columns;',
  '  const row = result[0].values[0];',
  '  const obj = {};',
  '  cols.forEach((c, i) => { obj[c] = row[i]; });',
  '  return obj;',
  '}',
  '',
  'function queryAll(db, sql, params) {',
  '  const result = db.exec(sql, params || []);',
  '  if (!result.length || !result[0].values.length) return [];',
  '  const cols = result[0].columns;',
  '  return result[0].values.map(row => {',
  '    const obj = {};',
  '    cols.forEach((c, i) => { obj[c] = row[i]; });',
  '    return obj;',
  '  });',
  '}',
  '',
  '// --- Session operations ---',
  'async function storeSession(opts) {',
  '  const db = await getDb();',
  '  const { id, summary, model, branch, working_dir } = opts;',
  "  db.run('INSERT OR REPLACE INTO sessions (id, started_at, summary, model, branch, working_dir) VALUES (?, ?, ?, ?, ?, ?)',",
  '    [id, now(), summary || null, model || null, branch || null, working_dir || null]);',
  '  saveDb(db);',
  '  return id;',
  '}',
  '',
  'async function endSession(id, summary) {',
  '  const db = await getDb();',
  "  const taskCount = queryOne(db, 'SELECT COUNT(*) as cnt FROM tasks WHERE session_id = ?', [id]);",
  "  const errorCount = queryOne(db, 'SELECT COUNT(*) as cnt FROM errors WHERE session_id = ?', [id]);",
  "  db.run('UPDATE sessions SET ended_at = ?, summary = ?, total_tasks = ?, total_errors = ? WHERE id = ?',",
  '    [now(), summary || null, taskCount ? taskCount.cnt : 0, errorCount ? errorCount.cnt : 0, id]);',
  '  saveDb(db);',
  '}',
  '',
  'async function getRecentSessions(limit) {',
  '  const db = await getDb();',
  "  return queryAll(db, 'SELECT * FROM sessions ORDER BY started_at DESC LIMIT ?', [limit || 10]);",
  '}',
  '',
  'async function getSession(id) {',
  '  const db = await getDb();',
  "  return queryOne(db, 'SELECT * FROM sessions WHERE id = ?', [id]);",
  '}',
  '',
  '// --- Task operations ---',
  'async function storeTask(opts) {',
  '  const db = await getDb();',
  '  const { session_id, description, status, result, skills_used, agents_used, files_modified } = opts;',
  "  db.run('INSERT INTO tasks (session_id, description, status, started_at, result, skills_used, agents_used, files_modified) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',",
  "    [session_id || null, description, status || 'in_progress', now(), result || null,",
  '     skills_used ? JSON.stringify(skills_used) : null,',
  '     agents_used ? JSON.stringify(agents_used) : null,',
  '     files_modified ? JSON.stringify(files_modified) : null]);',
  '  saveDb(db);',
  "  const row = queryOne(db, 'SELECT last_insert_rowid() as id');",
  '  return row ? row.id : null;',
  '}',
  '',
  'async function completeTask(taskId, result, filesModified) {',
  '  const db = await getDb();',
  '  db.run("UPDATE tasks SET status = \'completed\', completed_at = ?, result = ?, files_modified = ? WHERE id = ?",',
  '    [now(), result || null, filesModified ? JSON.stringify(filesModified) : null, taskId]);',
  '  saveDb(db);',
  '}',
  '',
  'async function getRecentTasks(limit) {',
  '  const db = await getDb();',
  "  return queryAll(db, 'SELECT * FROM tasks ORDER BY started_at DESC LIMIT ?', [limit || 20]);",
  '}',
  '',
  '// --- Learning operations ---',
  'async function storeLearning(opts) {',
  '  const db = await getDb();',
  '  const { session_id, category, content, importance, tags } = opts;',
  "  db.run('INSERT INTO learnings (session_id, category, content, importance, created_at, tags) VALUES (?, ?, ?, ?, ?, ?)',",
  "    [session_id || null, category, content, importance || 'normal', now(), tags ? JSON.stringify(tags) : null]);",
  '  saveDb(db);',
  "  const row = queryOne(db, 'SELECT last_insert_rowid() as id');",
  '  return row ? row.id : null;',
  '}',
  '',
  'async function searchLearnings(keyword, opts) {',
  '  const db = await getDb();',
  '  const limit = (opts && opts.limit) || 10;',
  '  const category = opts && opts.category;',
  "  let sql = 'SELECT * FROM learnings WHERE content LIKE ?';",
  "  const params = ['%' + keyword + '%'];",
  "  if (category) { sql += ' AND category = ?'; params.push(category); }",
  "  sql += ' ORDER BY created_at DESC LIMIT ?';",
  '  params.push(limit);',
  '  return queryAll(db, sql, params);',
  '}',
  '',
  'async function getImportantLearnings(limit) {',
  '  const db = await getDb();',
  '  return queryAll(db, "SELECT * FROM learnings WHERE importance IN (\'critical\', \'high\') ORDER BY created_at DESC LIMIT ?", [limit || 20]);',
  '}',
  '',
  '// --- Error operations ---',
  'async function storeError(opts) {',
  '  const db = await getDb();',
  '  const { session_id, error_type, error_message, fix_applied, file_path } = opts;',
  "  db.run('INSERT INTO errors (session_id, error_type, error_message, fix_applied, file_path, created_at) VALUES (?, ?, ?, ?, ?, ?)',",
  "    [session_id || null, error_type || 'unknown', error_message, fix_applied || null, file_path || null, now()]);",
  '  saveDb(db);',
  '}',
  '',
  'async function searchErrors(keyword, limit) {',
  '  const db = await getDb();',
  "  return queryAll(db, 'SELECT * FROM errors WHERE error_message LIKE ? OR fix_applied LIKE ? ORDER BY created_at DESC LIMIT ?',",
  "    ['%' + keyword + '%', '%' + keyword + '%', limit || 10]);",
  '}',
  '',
  '// --- Skills usage ---',
  'async function trackSkillUsage(opts) {',
  '  const db = await getDb();',
  '  const { skill_name, session_id, task_id, success, context } = opts;',
  "  db.run('INSERT INTO skills_used (skill_name, used_at, session_id, task_id, success, context) VALUES (?, ?, ?, ?, ?, ?)',",
  '    [skill_name, now(), session_id || null, task_id || null, success !== undefined ? (success ? 1 : 0) : 1, context || null]);',
  '  saveDb(db);',
  '}',
  '',
  'async function getSkillStats() {',
  '  const db = await getDb();',
  "  return queryAll(db, 'SELECT skill_name, COUNT(*) as usage_count, SUM(success) as success_count, MAX(used_at) as last_used FROM skills_used GROUP BY skill_name ORDER BY usage_count DESC');",
  '}',
  '',
  '// --- Knowledge base ---',
  'async function storeKnowledge(opts) {',
  '  const db = await getDb();',
  '  const { category, key, value, metadata } = opts;',
  "  db.run('INSERT OR REPLACE INTO knowledge (category, key, value, metadata, updated_at) VALUES (?, ?, ?, ?, ?)',",
  '    [category, key, value, metadata ? JSON.stringify(metadata) : null, now()]);',
  '  saveDb(db);',
  '}',
  '',
  'async function getKnowledge(category, key) {',
  '  const db = await getDb();',
  "  if (key) return queryOne(db, 'SELECT * FROM knowledge WHERE category = ? AND key = ?', [category, key]);",
  "  return queryAll(db, 'SELECT * FROM knowledge WHERE category = ? ORDER BY updated_at DESC', [category]);",
  '}',
  '',
  'async function searchKnowledge(keyword, limit) {',
  '  const db = await getDb();',
  "  return queryAll(db, 'SELECT * FROM knowledge WHERE value LIKE ? OR key LIKE ? ORDER BY updated_at DESC LIMIT ?',",
  "    ['%' + keyword + '%', '%' + keyword + '%', limit || 10]);",
  '}',
  '',
  '// --- Stats ---',
  'async function getStats() {',
  '  const db = await getDb();',
  "  const tables = ['sessions','conversations','tasks','skills_used','learnings','errors','embeddings','knowledge'];",
  '  const stats = {};',
  '  for (const table of tables) {',
  '    try {',
  "      const row = queryOne(db, 'SELECT COUNT(*) as cnt FROM ' + table);",
  '      stats[table] = row ? row.cnt : 0;',
  '    } catch (e) { stats[table] = 0; }',
  '  }',
  '  return stats;',
  '}',
  '',
  'module.exports = {',
  '  storeSession, endSession, getRecentSessions, getSession,',
  '  storeTask, completeTask, getRecentTasks,',
  '  storeLearning, searchLearnings, getImportantLearnings,',
  '  storeError, searchErrors,',
  '  trackSkillUsage, getSkillStats,',
  '  storeKnowledge, getKnowledge, searchKnowledge,',
  '  getStats, queryOne, queryAll, now,',
  '};',
  '',
  'if (require.main === module) {',
  '  const [,, cmd, ...args] = process.argv;',
  '  (async () => {',
  '    try {',
  '      switch (cmd) {',
  "        case 'stats': console.log(JSON.stringify(await getStats(), null, 2)); break;",
  "        case 'sessions': console.log(JSON.stringify(await getRecentSessions(parseInt(args[0]) || 5), null, 2)); break;",
  "        case 'search-learnings': console.log(JSON.stringify(await searchLearnings(args[0] || ''), null, 2)); break;",
  "        case 'search-errors': console.log(JSON.stringify(await searchErrors(args[0] || ''), null, 2)); break;",
  "        case 'skills': console.log(JSON.stringify(await getSkillStats(), null, 2)); break;",
  "        case 'knowledge': console.log(JSON.stringify(await getKnowledge(args[0], args[1]), null, 2)); break;",
  "        default: console.log('Commands: stats, sessions, search-learnings, search-errors, skills, knowledge');",
  '      }',
  "    } catch (e) { console.error('Error:', e.message); process.exit(1); }",
  '  })();',
  '}',
].join('\n'));

// =====================================================================
// FILE 3: .claude/helpers/memory-session-hook.cjs
// =====================================================================
writeFile('.claude/helpers/memory-session-hook.cjs', [
  '#!/usr/bin/env node',
  '/**',
  ' * Ruflow Memory System - Session Hook Integration',
  ' * Hooks into session lifecycle to record activity in the memory database.',
  ' */',
  '',
  "const path = require('path');",
  "const mq = require(path.join(__dirname, 'memory-query.cjs'));",
  '',
  '// Current session ID (set on session-start)',
  'let currentSessionId = null;',
  '',
  '// --- Hook: session-start ---',
  'async function onSessionStart(opts) {',
  "  const id = (opts && opts.id) || 'session-' + Date.now();",
  '  currentSessionId = id;',
  '  await mq.storeSession({',
  '    id: id,',
  '    model: (opts && opts.model) || null,',
  '    branch: (opts && opts.branch) || null,',
  '    working_dir: (opts && opts.working_dir) || process.cwd(),',
  '  });',
  '',
  '  // Load recent context for the session',
  '  const recentSessions = await mq.getRecentSessions(3);',
  '  const importantLearnings = await mq.getImportantLearnings(5);',
  '',
  "  console.log('Session started: ' + id);",
  '  if (recentSessions.length > 0) {',
  "    console.log('Recent sessions: ' + recentSessions.map(s => s.summary || s.id).join(', '));",
  '  }',
  '  if (importantLearnings.length > 0) {',
  "    console.log('Key learnings loaded: ' + importantLearnings.length);",
  '  }',
  '',
  '  return { sessionId: id, recentSessions, importantLearnings };',
  '}',
  '',
  '// --- Hook: session-end ---',
  'async function onSessionEnd(opts) {',
  '  const id = (opts && opts.id) || currentSessionId;',
  '  if (!id) return;',
  '  const summary = (opts && opts.summary) || null;',
  '  await mq.endSession(id, summary);',
  "  console.log('Session ended: ' + id);",
  '  currentSessionId = null;',
  '}',
  '',
  '// --- Hook: post-task ---',
  'async function onPostTask(opts) {',
  '  const { description, result, skills_used, agents_used, files_modified, success } = opts || {};',
  '  if (!description) return;',
  '',
  '  const taskId = await mq.storeTask({',
  '    session_id: currentSessionId,',
  '    description: description,',
  "    status: success === false ? 'failed' : 'completed',",
  '    result: result || null,',
  '    skills_used: skills_used || null,',
  '    agents_used: agents_used || null,',
  '    files_modified: files_modified || null,',
  '  });',
  '',
  '  // Track skill usage if provided',
  '  if (skills_used && Array.isArray(skills_used)) {',
  '    for (const skill of skills_used) {',
  '      await mq.trackSkillUsage({',
  '        skill_name: skill,',
  '        session_id: currentSessionId,',
  '        task_id: taskId,',
  '        success: success !== false,',
  '      });',
  '    }',
  '  }',
  '',
  "  console.log('Task recorded: ' + description.slice(0, 80));",
  '  return taskId;',
  '}',
  '',
  '// --- Hook: post-edit ---',
  'async function onPostEdit(opts) {',
  '  const { file_path, description } = opts || {};',
  '  if (!file_path) return;',
  '',
  '  await mq.storeKnowledge({',
  "    category: 'file_edits',",
  '    key: file_path,',
  "    value: description || 'File modified',",
  '    metadata: { session_id: currentSessionId, timestamp: mq.now() },',
  '  });',
  '}',
  '',
  '// --- Hook: on-error ---',
  'async function onError(opts) {',
  '  const { error_type, error_message, fix_applied, file_path } = opts || {};',
  '  if (!error_message) return;',
  '',
  '  await mq.storeError({',
  '    session_id: currentSessionId,',
  '    error_type: error_type,',
  '    error_message: error_message,',
  '    fix_applied: fix_applied,',
  '    file_path: file_path,',
  '  });',
  '',
  "  console.log('Error recorded: ' + (error_type || 'unknown') + ' - ' + error_message.slice(0, 80));",
  '}',
  '',
  '// --- Hook: on-learning ---',
  'async function onLearning(opts) {',
  '  const { category, content, importance, tags } = opts || {};',
  '  if (!content) return;',
  '',
  '  return await mq.storeLearning({',
  '    session_id: currentSessionId,',
  "    category: category || 'general',",
  '    content: content,',
  "    importance: importance || 'normal',",
  '    tags: tags,',
  '  });',
  '}',
  '',
  'function getCurrentSessionId() { return currentSessionId; }',
  '',
  'module.exports = {',
  '  onSessionStart, onSessionEnd, onPostTask, onPostEdit, onError, onLearning,',
  '  getCurrentSessionId,',
  '};',
  '',
  '// CLI',
  'if (require.main === module) {',
  '  const [,, cmd, ...args] = process.argv;',
  '  (async () => {',
  '    try {',
  '      switch (cmd) {',
  "        case 'start':",
  "          await onSessionStart({ id: args[0] || 'session-' + Date.now() });",
  '          break;',
  "        case 'end':",
  "          currentSessionId = args[0] || 'session-unknown';",
  '          await onSessionEnd({ id: args[0], summary: args[1] });',
  '          break;',
  "        case 'task':",
  "          currentSessionId = 'cli-session';",
  '          await onPostTask({ description: args.join(" ") || "CLI task" });',
  '          break;',
  '        default:',
  "          console.log('Usage: memory-session-hook.cjs <start|end|task> [args...]');",
  '      }',
  "    } catch (e) { console.error('Error:', e.message); process.exit(1); }",
  '  })();',
  '}',
].join('\n'));

// =====================================================================
// FILE 4: scripts/memory-status.js
// =====================================================================
writeFile('scripts/memory-status.js', [
  '#!/usr/bin/env node',
  '/**',
  ' * Ruflow Memory Status - Shows database stats and recent activity.',
  ' * Run: node scripts/memory-status.js',
  ' */',
  '',
  "const path = require('path');",
  "const fs = require('fs');",
  "const mq = require(path.join(__dirname, '..', '.claude', 'helpers', 'memory-query.cjs'));",
  "const { DB_PATH } = require(path.join(__dirname, '..', '.claude', 'helpers', 'memory-init.cjs'));",
  '',
  'const C = {',
  "  reset: '\\x1b[0m', bold: '\\x1b[1m', dim: '\\x1b[2m',",
  "  green: '\\x1b[32m', cyan: '\\x1b[36m', yellow: '\\x1b[33m',",
  "  red: '\\x1b[31m', bgBlue: '\\x1b[44m', white: '\\x1b[37m',",
  '};',
  '',
  '(async () => {',
  '  try {',
  "    console.log('\\n' + C.bgBlue + C.white + C.bold + ' Ruflow Memory Status ' + C.reset + '\\n');",
  '',
  '    // Database info',
  "    console.log(C.dim + 'Database: ' + C.cyan + DB_PATH + C.reset);",
  '    if (fs.existsSync(DB_PATH)) {',
  '      const size = fs.statSync(DB_PATH).size;',
  "      console.log(C.dim + 'Size:     ' + C.cyan + (size / 1024).toFixed(1) + ' KB' + C.reset);",
  '    } else {',
  "      console.log(C.red + 'Database not found! Run: node .claude/helpers/memory-init.cjs' + C.reset);",
  '      process.exit(1);',
  '    }',
  '',
  '    // Stats',
  '    const stats = await mq.getStats();',
  "    console.log('\\n' + C.bold + 'Record Counts:' + C.reset);",
  '    for (const [table, count] of Object.entries(stats)) {',
  "      console.log('  ' + table.padEnd(16) + C.cyan + count + C.reset);",
  '    }',
  '',
  '    // Recent sessions',
  '    const sessions = await mq.getRecentSessions(5);',
  '    if (sessions.length > 0) {',
  "      console.log('\\n' + C.bold + 'Recent Sessions:' + C.reset);",
  '      for (const s of sessions) {',
  "        const summary = s.summary ? s.summary.slice(0, 60) : 'No summary';",
  "        const date = s.started_at ? s.started_at.slice(0, 19) : 'unknown';",
  "        console.log('  ' + C.cyan + date + C.reset + '  ' + summary);",
  '      }',
  '    }',
  '',
  '    // Skill stats',
  '    const skills = await mq.getSkillStats();',
  '    if (skills.length > 0) {',
  "      console.log('\\n' + C.bold + 'Most Used Skills:' + C.reset);",
  '      for (const s of skills.slice(0, 10)) {',
  "        console.log('  ' + s.skill_name.padEnd(30) + C.cyan + s.usage_count + C.reset + ' uses');",
  '      }',
  '    }',
  '',
  '    // Recent learnings',
  '    const learnings = await mq.getImportantLearnings(3);',
  '    if (learnings.length > 0) {',
  "      console.log('\\n' + C.bold + 'Important Learnings:' + C.reset);",
  '      for (const l of learnings) {',
  "        console.log('  [' + C.yellow + l.importance + C.reset + '] ' + l.content.slice(0, 80));",
  '      }',
  '    }',
  '',
  "    console.log('\\n' + C.green + C.bold + 'Memory system operational.' + C.reset + '\\n');",
  '',
  "  } catch (e) { console.error(C.red + 'Status check failed: ' + e.message + C.reset); process.exit(1); }",
  '})();',
].join('\n'));

// =====================================================================
// FILE 5: .claude/skills/ruflow-memory/SKILL.md
// =====================================================================
writeFile('.claude/skills/ruflow-memory/SKILL.md', [
  '# Ruflow Memory System',
  '',
  'Persistent vector database memory for cross-session context. Uses sql.js (WASM SQLite) for cross-platform operation.',
  '',
  '## Database Location',
  '',
  '- **Project DB**: `data/memory/ruflow.db`',
  '- **AgentDB**: `C:\\Users\\Qadri Laptop\\.claude\\projects\\D--Personal-Smarter-revolution-Ruflow\\memory\\agentdb.sqlite`',
  '',
  '## Quick Reference',
  '',
  '### Initialize Database',
  '```bash',
  'node .claude/helpers/memory-init.cjs',
  '```',
  '',
  '### Check Status',
  '```bash',
  'node scripts/memory-status.js',
  '```',
  '',
  '### Query Memory (CLI)',
  '```bash',
  '# Show database stats',
  'node .claude/helpers/memory-query.cjs stats',
  '',
  '# List recent sessions',
  'node .claude/helpers/memory-query.cjs sessions 5',
  '',
  '# Search learnings by keyword',
  'node .claude/helpers/memory-query.cjs search-learnings "authentication"',
  '',
  '# Search past errors',
  'node .claude/helpers/memory-query.cjs search-errors "ENOENT"',
  '',
  '# Show skill usage statistics',
  'node .claude/helpers/memory-query.cjs skills',
  '',
  '# Get knowledge by category',
  'node .claude/helpers/memory-query.cjs knowledge "file_edits"',
  '```',
  '',
  '### Search Existing AgentDB',
  '```bash',
  'node scripts/memory-db/search.js "pizza website"',
  'node scripts/memory-db/search.js --type session "authentication"',
  'node scripts/memory-db/search.js --recent 7 "memory system"',
  '```',
  '',
  '## Programmatic Usage',
  '',
  '### Store a Session',
  '```javascript',
  "const mq = require('./.claude/helpers/memory-query.cjs');",
  '',
  "await mq.storeSession({ id: 'session-123', summary: 'Built auth module', model: 'opus' });",
  "await mq.endSession('session-123', 'Completed OAuth integration');",
  '```',
  '',
  '### Store a Task',
  '```javascript',
  'const taskId = await mq.storeTask({',
  "  session_id: 'session-123',",
  "  description: 'Implement login endpoint',",
  "  skills_used: ['api-design', 'auth-implementation'],",
  "  files_modified: ['src/auth/login.ts', 'tests/auth.test.ts'],",
  '});',
  "await mq.completeTask(taskId, 'Login endpoint working with JWT tokens');",
  '```',
  '',
  '### Store a Learning',
  '```javascript',
  'await mq.storeLearning({',
  "  session_id: 'session-123',",
  "  category: 'architecture',",
  "  content: 'Use middleware pattern for auth instead of decorators - better testability',",
  "  importance: 'high',",
  "  tags: ['auth', 'patterns', 'testing'],",
  '});',
  '```',
  '',
  '### Store an Error and Fix',
  '```javascript',
  'await mq.storeError({',
  "  session_id: 'session-123',",
  "  error_type: 'build_error',",
  "  error_message: 'Cannot find module sql.js',",
  "  fix_applied: 'Run npm install in scripts/memory-db/',",
  "  file_path: 'scripts/memory-db/lib.js',",
  '});',
  '```',
  '',
  '### Search Past Knowledge',
  '```javascript',
  "const learnings = await mq.searchLearnings('authentication');",
  "const errors = await mq.searchErrors('ENOENT');",
  "const knowledge = await mq.searchKnowledge('middleware');",
  '```',
  '',
  '### Store and Retrieve Knowledge',
  '```javascript',
  'await mq.storeKnowledge({',
  "  category: 'project_config',",
  "  key: 'auth_provider',",
  "  value: 'JWT with refresh tokens',",
  "  metadata: { decided_on: '2026-04-07' },",
  '});',
  '',
  "const config = await mq.getKnowledge('project_config', 'auth_provider');",
  '```',
  '',
  '### Track Skill Usage',
  '```javascript',
  'await mq.trackSkillUsage({',
  "  skill_name: 'sparc-methodology',",
  "  session_id: 'session-123',",
  '  success: true,',
  "  context: 'Used for API design phase',",
  '});',
  '',
  'const skillStats = await mq.getSkillStats();',
  '```',
  '',
  '### Session Hooks',
  '```javascript',
  "const hooks = require('./.claude/helpers/memory-session-hook.cjs');",
  '',
  '// Start a session (loads recent context)',
  "const ctx = await hooks.onSessionStart({ id: 'session-123', model: 'opus' });",
  '',
  '// Record a completed task',
  "await hooks.onPostTask({ description: 'Built login page', skills_used: ['react-patterns'] });",
  '',
  '// Record a learning',
  "await hooks.onLearning({ category: 'performance', content: 'Lazy load auth module', importance: 'high' });",
  '',
  '// Record an error and its fix',
  "await hooks.onError({ error_type: 'runtime', error_message: 'Token expired', fix_applied: 'Added refresh logic' });",
  '',
  '// End the session',
  "await hooks.onSessionEnd({ summary: 'Auth system complete' });",
  '```',
  '',
  '## Database Schema',
  '',
  '| Table | Purpose |',
  '|-------|---------|',
  '| `sessions` | Session records with timestamps, model, branch |',
  '| `conversations` | Conversation entries per session |',
  '| `tasks` | Task descriptions, status, skills/agents/files |',
  '| `skills_used` | Skill usage tracking with success rates |',
  '| `learnings` | Decisions, patterns, insights with importance levels |',
  '| `errors` | Errors encountered and fixes applied |',
  '| `embeddings` | Vector embeddings for semantic search |',
  '| `knowledge` | Key-value knowledge base by category |',
  '| `search_chunks` | Full-text search index |',
  '',
  '## Architecture',
  '',
  '- **sql.js (WASM)**: Cross-platform SQLite, no native compilation needed',
  '- **Location**: `scripts/memory-db/node_modules/sql.js/`',
  '- **TF-IDF Search**: Built-in term-frequency search in `scripts/memory-db/lib.js`',
  '- **Dual DB**: Project-local `ruflow.db` + Claude auto-memory `agentdb.sqlite`',
].join('\n'));

console.log('\nAll 4 remaining files generated successfully.');
console.log('Total files in memory system: 5');
console.log('  1. .claude/helpers/memory-init.cjs (already existed)');
console.log('  2. .claude/helpers/memory-query.cjs');
console.log('  3. .claude/helpers/memory-session-hook.cjs');
console.log('  4. scripts/memory-status.js');
console.log('  5. .claude/skills/ruflow-memory/SKILL.md');
